#ifndef QT_COMMON_HPP
#define QT_COMMON_HPP

#include <QApplication>
#include <QWidget>
#include <QMainWindow>
#include <QDialog>
#include <QObject>
#include <QCoreApplication>
#include <QEvent>
#include <QTimer>
#include <QLabel>
#include <QPushButton>
#include <QLineEdit>
#include <QTextEdit>
#include <QTextBrowser>
#include <QPlainTextEdit>
#include <QComboBox>
#include <QCheckBox>
#include <QRadioButton>
#include <QSpinBox>
#include <QDoubleSpinBox>
#include <QSlider>
#include <QProgressBar>
#include <QListView>
#include <QTreeView>
#include <QTableView>
#include <QListWidget>
#include <QTreeWidget>
#include <QTableWidget>
#include <QGroupBox>
#include <QFrame>
#include <QScrollArea>
#include <QTabWidget>
#include <QTableWidget>
#include <QStackedWidget>
#include <QToolBox>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QFormLayout>
#include <QStackedLayout>
#include <QBoxLayout>
#include <QMessageBox>
#include <QInputDialog>
#include <QFileDialog>
#include <QColorDialog>
#include <QFontDialog>
#include <QProgressDialog>
#include <QDialogButtonBox>
#include <QButtonGroup>
#include <QTabBar>
#include <QToolBar>
#include <QMenuBar>
#include <QMenu>
#include <QAction>
#include <QToolButton>
#include <QSplitter>
#include <QDockWidget>
#include <QStatusBar>
#include <QString>
#include <QHeaderView>

#endif